services:
  - type: web
    name: autott
    env: node
    buildCommand: |
      # Install system dependencies including Tesseract
      apt-get update -y
      apt-get install -y tesseract-ocr
      apt-get install -y python3-pip
      apt-get install -y python3-opencv
      # Install Python dependencies
      cd frontend
      npm install
      npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://autott-backend.onrender.com

  - type: web
    name: autott-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FRONTEND_URL
        value: https://autott.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_PROJECT_ID
        sync: false 